# Site settings
name: Devin Reams
title: Devin Reams
tagline: "Sensibly impulsive, consistently non-committal, and passionately impartial. I help with Enterprise Accounts at GitHub."

email: devin@reams.me
url: "http://devinreams.github.io"
version: 1.0

# Build settings
markdown: kramdown
permalink: pretty
paginate: 10
paginate_path: '/page/:num'