# Site settings
name: Devin Reams
title: Devin Reams
sub-title: ""
description: "Personal website of Devin Reams, technologist in Colorado."
intro: "Hi! I'm [Devin](/about/). I'm sensibly impulsive, consistently non-committal, and passionately impartial. I'm a technologist living in Denver, Colorado."

email: devin@reams.me
url: "https://devin.rea.ms"
version: 2.7.6

# Build settings
permalink: /:year/:title/
paginate: 10
paginate_path: "/page/:num/"

plugins:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-feed
- jekyll-paginate
