# Site settings
name: Devin Reams
title: Devin Reams
sub-title: ""
description: "Personal website of Devin Reams, engineering manager for mobile at Smartsheet."
intro: "Hi! I'm [Devin](/about/) and I work at Smartsheet. I'm sensibly impulsive, consistently non-committal, and passionately impartial."

email: devin@reams.me
url: "https://devin.reams.me"
version: 2.5.2

# Build settings
permalink: /:year/:title/
paginate: 10
paginate_path: "/page/:num/"

plugins:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-feed
- jekyll-paginate
