# Site settings
name: Devin Reams
title: Devin Reams
email: devin@reams.me
description: "Sensibly impulsive, consistently non-committal, and passionately impartial. I help with Enterprise Accounts at GitHub."
baseurl: ""
url: "http://devinreams.github.io"

# Build settings
markdown: kramdown
permalinks: pretty
