# Site settings
name:			Devin Reams
email:			devin@reams.me
url:			"http://devinreams.github.io"
description: 	"Sensibly impulsive, consistently non-committal, and passionately impartial. I help with Enterprise Accounts at GitHub."

# Build settings
markdown:         kramdown
pygments:         true
permalink:        pretty
paginate:         11
