# Site settings
name: Devin Reams
title: Devin Reams
sub-title: ""
description: "Personal website of Devin Reams, businessperson at GitHub."
intro: "Hi! I'm [Devin](/about/) and I help with business systems at [GitHub](https://github.com/about). I'm sensibly impulsive, consistently non-committal, and passionately impartial."

email: devin@reams.me
url: "https://devin.reams.me"
version: 2.3.1

# Build settings
permalink: /:year/:title/
paginate: 10
paginate_path: "/page/:num/"

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-feed
- jekyll-paginate
