# Site settings
name: Devin Reams
title: Devin Reams
sub-title: ""
description: "Personal website of Devin Reams, sales ops at GitHub."
intro: "I'm [Devin Reams](/about/) and I help with sales at [GitHub](https://github.com). I'm sensibly impulsive, consistently non-committal, and passionately impartial."

email: devin@reams.me
url: "https://devin.reams.me"
version: 1.5

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["strikethrough", "footnotes"]
permalink: /:year/:title/
paginate: 10
paginate_path: "/page/:num/"

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
