# Site settings
name: Devin Reams
title: Devin Reams
sub-title: ""
description: "Personal website of Devin Reams, sales ops at GitHub."
intro: "I'm [Devin Reams](/about/) and I help with sales at [GitHub](https://github.com). I'm sensibly impulsive, consistently non-committal, and passionately impartial."

email: devin@reams.me
url: "http://devin.reams.me"
version: 1.4

# Build settings
markdown: kramdown
permalink: /:year/:title/
paginate: 10
paginate_path: "/page/:num/"

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
